version: 2
updates:
  # Keep frontend Docker image up to date
  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps(docker-frontend)"