# frontend/Dockerfile.final
FROM nginx:1.29.1-alpine
RUN echo "Triggering cache bust for next layer."
COPY dist-exported /usr/share/nginx/html
COPY build-timestamp.txt /usr/share/nginx/html/build-timestamp.txt
COPY nginx.conf /etc/nginx/nginx.conf
# Serve API via Ingress; or add simple proxy config if co-hosting