{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-assistant.fullname" . }}-secret
type: Opaque
stringData:
  API_KEY: {{ .Values.secret.apiKey | quote }}
{{- end }}