apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-assistant.fullname" . }}-backend
  labels:
    app: {{ include "k8s-assistant.name" . }}
    component: backend
spec:
  type: {{ .Values.service.backend.type }}
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: {{ .Values.service.backend.port }}
      protocol: TCP
  selector:
    app: {{ include "k8s-assistant.name" . }}
    component: backend