apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-assistant.fullname" . }}-frontend
  labels:
    app: {{ include "k8s-assistant.name" . }}
    component: frontend
spec:
  type: {{ .Values.service.frontend.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: {{ .Values.service.frontend.port }}
      protocol: TCP
  selector:
    app: {{ include "k8s-assistant.name" . }}
    component: frontend