{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-assistant.serviceAccountName" . }}
  labels:
    app: {{ include "k8s-assistant.name" . }}
{{- end }}