{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
stringData:
  api-key: {{ required "You must provide .Values.secret.apiKey" .Values.secret.apiKey | quote }}
{{- end }}