apiVersion: v1
entries:
  k8s-assistant:
  - apiVersion: v2
    appVersion: 0.2.27
    created: "2025-09-04T07:19:41.104466333Z"
    description: AI-Powered Web Assistant for Kubernetes clusters that lets you query
      and interact with your cluster in natural language
    digest: 25bc307ef56087eeca80034e13fdb572227d6e271dedcc7bda219e99004ec098
    icon: https://raw.githubusercontent.com/CatalinPredica/k8s-assistant/main/helm/logo.svg
    name: k8s-assistant
    type: application
    urls:
    - https://catalinpredica.github.io/k8s-assistant/charts/k8s-assistant-0.1.30.tgz
    version: 0.1.30
generated: "2025-09-04T07:19:41.103957789Z"
