apiVersion: v1
entries:
  k8s-assistant:
  - apiVersion: v2
    appVersion: 0.2.17
    created: "2025-09-02T05:55:14.472387141Z"
    description: AI-Powered Web Assistant for Kubernetes clusters that lets you query
      and interact with your cluster in natural language
    digest: 811df9d8326f550a442071f9c72721d0bf28a05bb66a64cd1586f48afb954fe9
    name: k8s-assistant
    type: application
    urls:
    - https://catalinpredica.github.io/k8s-assistant/charts/k8s-assistant-0.1.19.tgz
    version: 0.1.19
generated: "2025-09-02T05:55:14.47187157Z"
