apiVersion: k8s-assistant.io/v1alpha1
kind: K8sAssistant
metadata:
  name: my-assistant
  namespace: k8s-assistant
spec:
  version: "0.2.41"
  apiKeySecretRef: "gemini-api-key"
  replicas:
    frontend: 1
    backend: 1