apiVersion: v2
name: k8s-assistant
description: AI-Powered Web Assistant for Kubernetes clusters that lets you query and interact with your cluster in natural language
type: application
version: 0.1.44
appVersion: "0.2.40"
icon: https://raw.githubusercontent.com/CatalinPredica/k8s-assistant/main/helm/logo.svg
