replicaCount: 1
image:
  backend:
    repository: catalinpredica/k8s-assistant-backend
    tag: "1.0.6"
    pullPolicy: IfNotPresent
  frontend:
    repository: catalinpredica/k8s-assistant-frontend
    tag: "0.1.4"
    pullPolicy: IfNotPresent
service:
  backend:
    type: ClusterIP
    port: 8000
    targetPort: 8000
  frontend:
    type: ClusterIP
    port: 80
    targetPort: 80
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
serviceAccount:
  create: true
  name: ""
rbac:
  create: true
config:
  BACKEND_LOG_LEVEL: info
# Configuration for the Gemini API key secret.
secret:
  enabled: true
  name: "k8s-assistant-gemini-secret"
  apiKey: "" # users must provide their own API key here
env:
  GEMINI_MODEL: "gemini-2.5-flash"
