replicaCount: 1

image:
  backend:
    repository: catalinpredica/k8s-assistant-backend
    tag: "0.3.6"
    pullPolicy: IfNotPresent
  frontend:
    repository: catalinpredica/k8s-assistant-frontend
    tag: "0.1.9"
    pullPolicy: IfNotPresent

service:
  backend:
    type: ClusterIP
    port: 8000
    targetPort: 8000
  frontend:
    type: ClusterIP
    port: 80
    targetPort: 80

ingress:
  enabled: false
  className: nginx
  hosts:
    - host: assistant.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

serviceAccount:
  create: true
  name: ""

rbac:
  create: true

config:
  BACKEND_LOG_LEVEL: info

# Configuration for the Gemini API key secret.
# IMPORTANT: You must create this secret manually before deploying the chart.
# For example: kubectl create secret generic k8s-assistant-gemini-secret --from-literal=api-key='YOUR_API_KEY'
secret:
  enabled: true
  name: "k8s-assistant-gemini-secret"
  apiKey: "AIzaSyC1amKfTo7I7VNGNDjALLMbLqodMc-CYm0"

env:
  GEMINI_MODEL: "gemini-2.5-flash"
