apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: k8sassistants.k8s-assistant.io
spec:
  group: k8s-assistant.io
  names:
    kind: K8sAssistant
    plural: k8sassistants
    singular: k8sassistant
    shortNames:
      - k8sa
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                version:
                  type: string
                apiKeySecretRef:
                  type: string
                replicas:
                  type: object
                  properties:
                    frontend:
                      type: integer
                    backend:
                      type: integer
            status:
              type: object
              properties:
                phase:
                  type: string
                frontendURL:
                  type: string