name: K8S Assistant - Frontend Docker Build and Push

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-docker-build.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch all remote tags
        run: git fetch --tags --force

      - name: Set up QEMU (for cross-platform builds)
        uses: docker/setup-qemu-action@v3 # Use v3 for latest features

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Use v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3 # Use v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version from git tags and bump semver
        id: version
        run: |
          latest_tag=$(git tag | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1)
          if [ -z "$latest_tag" ]; then
            latest_tag="0.1.0"
          fi
          IFS='.' read -r major minor patch <<< "$latest_tag"
          commit_msg=$(git log -1 --pretty=%B)
          if echo "$commit_msg" | grep -q '\[major\]'; then
            major=$((major+1))
            minor=0
            patch=0
          elif echo "$commit_msg" | grep -q '\[minor\]'; then
            minor=$((minor+1))
            patch=0
          else
            patch=$((patch+1))
          fi
          new_tag="$major.$minor.$patch"
          echo "version=$new_tag" >> $GITHUB_OUTPUT

      - name: Build, Scan, and Push Docker image
        uses: docker/build-push-action@v5 # Using the latest, most reliable action
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            catalinpredica/k8s-assistant-frontend:${{ steps.version.outputs.version }}
            catalinpredica/k8s-assistant-frontend:latest
          provenance: |
            trivy:
              enabled: true
              severity: 'MEDIUM,HIGH,CRITICAL'
              exit-code: 1
              format: 'table'
              output: 'trivy-report.txt'

      # The following steps are for updating Git tags, Helm, and README, and remain unchanged
      # They will now only run if the build and scan succeed
      - name: Set up Git for pushing tags
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
          git config user.name "GitHub Actions"
          git config user.email "catalinpredica@gmail.com"  
                        
      - name: Create Git tag for new version
        run: |
          git fetch --tags
          if git rev-parse ${{ steps.version.outputs.version }} >/dev/null 2>&1; then
            echo "Tag ${{ steps.version.outputs.version }} already exists. Skipping tag creation."
            exit 0
          fi
          git config user.name "GitHub Actions"
          git config user.email "catalinpredica@gmail.com"
          git tag ${{ steps.version.outputs.version }}
          git push origin ${{ steps.version.outputs.version }}
          
      - name: Update Helm values.yaml with new frontend image tag
        run: |
          yq -i '.image.frontend.tag = "${{ steps.version.outputs.version }}"' helm/values.yaml
          echo "Updated helm/values.yaml frontend tag to ${{ steps.version.outputs.version }}"
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add helm/values.yaml
          git commit -m "chore: update helm/values.yaml to image tag ${{ steps.version.outputs.version }}" || echo "No changes to commit"
          git push origin HEAD:${GITHUB_REF#refs/heads/}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Update README.md with latest release
        run: |
          latest_tag=${{ steps.version.outputs.version }}
          latest_url="https://github.com/${{ github.repository }}/releases/tag/$latest_tag"
          readme="README.md"
          sed -i "s|^The latest release is .*|The latest release is [$latest_tag]($latest_url)|" "$readme"
          git config user.name "GitHub Actions"
          git config user.email "catalinpredica@gmail.com"
          git add "$readme"
          git commit -m "docs: update README.md with latest release $latest_tag" || echo "No changes to commit"
          git push origin HEAD:${GITHUB_REF#refs/heads/}