name: Validate Frontend Base Image

on:
  pull_request:
    branches: [main]
    paths:
      - 'frontend/Dockerfile'
    types: [opened, synchronize, reopened]

jobs:
  validate-base-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build Docker image locally
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          load: true
          push: false
          pull: true   # always pull latest base image
          tags: k8s-assistant-frontend:scan

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@v0.31.0
        with:
          image-ref: k8s-assistant-frontend:scan
          exit-code: 1      # fail on vulnerabilities
          severity: HIGH,CRITICAL

      - name: Run frontend tests
        run: |
          npm install
          npm test