name: Validate Frontend Base Image

on:
  pull_request:
    branches: [main]
    paths:
      - 'frontend/Dockerfile'
    types: [opened, synchronize, reopened]

jobs:
  validate-base-image:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build Docker image locally
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          load: true
          push: false
          pull: true   # always pull latest base image
          tags: k8s-assistant-frontend:scan

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@0.33.0
        with:
          image-ref: k8s-assistant-frontend:scan
          exit-code: 1      # fail on vulnerabilities
          severity: HIGH,CRITICAL

      - name: Test built Docker image
        run: |
          # Run the built image in a temporary container
          docker run -d --name test-frontend -p 8080:80 k8s-assistant-frontend:scan
          
          # Give it a few seconds to start
          sleep 5
          
          # Smoke test: check if Nginx serves index.html
          curl -f http://localhost:8080 || (docker logs test-frontend && exit 1)
          
          # Stop and remove the container
          docker stop test-frontend
          docker rm test-frontend